### ISSUE TITLE
你好，我想请教下新手如何加入到COC里？

### ISSUE THREAD

**Issue by willcream** [NoahBox/noahbox.github.io#1]
你好，我在你博客怎么都找不到联系方式，不得已以这种方式打招呼，如有打扰实属抱歉。

首先非常感谢你放在博客里的规则书，这是我见过最美观的一版。

本次联系是想了解下以下几点：
1. 怎么在完全不认识人的情况下加入到COC里？
2. 去网团之前要做好什么准备？通读规则书就够了嘛？
3. 去哪里参加网团的活跃度较高？
4. 作为新人怎样才能避免被人家嫌弃？有没有什么雷区？

我忘了是什么原因被COC吸引了，有好几个月了，目前刚开始看规则书，之前看过一些别人的跑团视频，也加入过一些QQ群但一直没有跟别人开过团（平时工作忙，真遇到开的时候也不好意思加入，怕鸽）。之前也多次企图去猫爷TRPG 上面围观别人跑团，但好想他们只在上面roll点……

由于我四处安利朋友不成功，甚至不少人把COC当成了“部落冲突”，因此我觉得如果真要玩可能网团是唯一出路……

若能解答则十分感谢~如果打扰到你了，我就看看怎么删了这个issue……

**Comment by NoahBox** [comment]
我真的没想到会有人在博客的 github 仓库通过提 issue 的方式向我问问题，所以看到得比较晚。

接下来，我对你的问题进行一一回答。不过这仅限于我的个人想法，仅供参考。

1.  最简单的办法是，加一个与 COC 相关的群。什么群都好，只要和 COC 有关往往就会有 KP 发布网团招募信息。这样的群一般在一些跑团社群可以找到，例如 Dicecho、魔都TRPG、纯美苹果园 或 100DICE 之类。在这些社群里也经常会有 KP 发布招募信息。
2. 至少应该读完调查员手册，读完守密人规则书就更好了。此外，建议可以看一看《克苏鲁神话》的原著，了解一下你将要游玩的游戏是基于什么背景而设立的；或者可以看一看优秀的 Replay 视频，不过要注意甄别，一些 Replay 中可能会包含误导新人的内容，注意 Replay 作者的视频简介或者注意信息。
3. 一般来说网团大多在 QQ 群里进行，不过偶尔也有使用别的平台的情况。顺便推荐一个叫做 Dodo 的平台，其中就有 COC 板块。
4. 最重要的一点是：不要鸽！如果实在有事情，一定要提前一两天和 KP 沟通。其次，要记住，包括 COC 在内的所有 TRPG 游戏中，主持人和玩家从来都不是对立的关系，请善待你的 KP。另外，规则并不是 TRPG 的核心，最重要的是大家玩得愉快，所以不要太过在意你的 KP 没有严格按照规则行事（当然，前提是不要太离谱）。

如果还有什么别的问题，欢迎通过邮件或者 QQ 和我交流。我的联系方式可以在博客的侧边栏（默认是收起的，点击左下角的按钮以展开）里找到。

**Comment by willcream** [comment]
非常感谢你详细的解答，我看到你写这么细致也让我降低了参加网团的心理负担。另外，我找到你博客里的联系方式了，我漏掉了“站点概览”……

**Comment by NoahBox** [comment]
很高兴帮到了你，希望你可以玩得愉快。
